{
 "title": "Аналитика сервисов",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Количество событий во времени",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT service_name, count(service_name) count_events FROM cleverlog.logs GROUP BY service_name LIMIT 100"
    }
   ]
  },
  {
   "title": "Журнал сообщений",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT message, service_name, tstamp, src FROM cleverlog.logs LIMIT 100"
    }
   ]
  },
  {
   "title": "Трассировка запросов в сервисах",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT span_id, service_name, tstamp, count(span_id) FROM cleverlog.logs GROUP BY tstamp, span_id, service_name LIMIT 100"
    }
   ]
  },
  {
   "title": "Коеффициент отказоустойчивости",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT service_name as service,\n       (SELECT count(*) FROM cleverlog.logs WHERE log_level = 'Error' AND service_name = service_name) /\n       (SELECT count(*) FROM cleverlog.logs WHERE service_name = service_name)\nFROM cleverlog.logs GROUP BY service_name LIMIT 100"
    }
   ]
  },
  {
   "title": "Типы событий в сервисе",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT service_name, log_level, count(log_level) FROM cleverlog.logs GROUP BY service_name, log_level LIMIT 100"
    }
   ]
  }
 ]
}