version: '3.9'
services:
  clickHouse:
    image: yandex/clickhouse-server
    environment:
      CLICKHOUSE_DB: cleverlog
      CLICKHOUSE_USER: cleveruser
      CLICKHOUSE_PASSWORD: cleverpswd
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    volumes:
      - clickhouse-data:/var/lib/clickhouse

  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      GF_INSTALL_PLUGINS: grafana-clickhouse-datasource
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: "/var/lib/grafana/dashboards/clever.json"
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/vat/lib/grafana

volumes:
  clickhouse-data:
  grafana_data:
